# -*- coding: utf-8 -*-
"""week67舊版.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p1JtvFrz_MKr7auNm9YUX_f3jYgKvltp
"""

player = "Ron Harper"
player_list = ["Ron Harper", "Michael Jordan", "Scottie Pippen", "Dennis Rodman","LucLongley"]
player_tuple = tuple(player_list)
player_dict = {
"PG": "Ron Harper",
"SG": "Michael Jordan",
"SF": "Scottie Pippen",
"PF": "Dennis Rodman",
"C": "Luc Longley"}
player_set = set(player_list)
print(type(player))
print(type(player_list))
print(type(player_tuple))
print(type(player_dict))
print(type(player_set))

s1 = '春眠不覺曉,處處聞啼鳥。'
print(s1)

s2 = "夜來風雨聲,花落知多少。"
print(s2)

s3 = '作者"孟浩然" 詩名"春曉"'
print(s3)
s4 = "作者'孟浩然' 詩名'春曉'"
print(s4)

s5 = ''' 春眠不覺曉,處處聞啼鳥。
夜來風雨聲,花落知多少。
作者"孟浩然" 詩名"春曉"
'''
print(s5)

s1 ="123"
s2 = "456"
s3 = s1 + s2
print(s3)

s4 = s1 * 2
print(s4)

s5 = '春眠不覺曉,處處聞啼鳥。\n\
夜來風雨聲,花落知多少。\n\
\t作者"孟浩然" 詩名"春曉"'
print(s5)

s = '0123456789'
print(s[0])
print('s[1]=', s[1])
print(s[-1])
print('s[-2]=', s[-2])

s = '0123456789'
print('s=', s, 's[:]=', s[:])
print('s=', s, 's[5:]=', s[5:])
print('s=', s, 's[-2:]=', s[-2:])
print('s=', s, 's[:5]=', s[:5])
print('s=', s, 's[:-2]=', s[:-2])
print('s=', s, 's[7:9]=', s[7:9])
print('s=', s, 's[-4:-1]=', s[-4:-1])
print('s=', s, 's[5:-2]=', s[5:-2])
print('s=', s, 's[2:10:2]=', s[2:10:2])
print('s=', s, 's[::-1]=', s[::-1])
print('s=', s, 's[-1::-1]=', s[-1::-1])

s = '春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
print(len(s))

s = '春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
list1 = s.split(',')
print(list1)

list1 = ['春眠不覺曉','處處聞啼鳥','夜來風雨聲','花落知多少。']
s2=','.join(list1) 
print(s2)

s1='春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
print(s1.find('花落'))

s1='春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
print(s1.count('處'))

s1='春眠不覺曉,處處聞啼鳥,夜來風雨聲,花落知多少。'
s3=s1.replace('春','冬')
print(s3)

s1='An apple a day.'
print(s1.capitalize())

s1='An apple a day.'
print(s1.swapcase())

s1='An apple a day.'
print(s1.upper())

s1='An apple a day.'
print(s1.lower())

t1 = ()
print(t1)
t2 = ('z', )
print(t2)
t3 = (1, 2, 3)
print(t3)
t4 = (1,2,3,4)
t5 = (t4,5,6)
print(t5)

list1=[1,2,3,4]
t6 = tuple(list1)
print(t6)

t1= (1,2,3,4)
t2 = (5,6,t2)
print(len(t2))
print(t2[0])
print(t2[2][0])

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
print('購物清單shoplist為')
print(shoplist)
listm = [1, 2.0, 'Python']
print("串列可以包含各種資料型別的元素")
print(listm)

tuple2 = ('a', 'b', 1, 2)
list2 = list(tuple2)
print(list2)

shoplist1 = ['牛奶', '蛋', '咖啡豆']
shoplist2 = ['西瓜', '鳳梨']
shoplist_all = shoplist1 + shoplist2
print(shoplist_all)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
print('顯示shoplist[0]為',shoplist[0])
index = shoplist.index('咖啡豆')
print("執行 index = shoplist.index('咖啡豆') 後")
print('index=', index)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
shoplist[1] = '皮蛋'
print("執行 shoplist[1] = '皮蛋' 後")
print(shoplist)

shoplist = ['牛奶', '蛋', '咖啡豆', '西瓜', '鳳梨']
a = list('abcdefghijk')
print('a[:]為', a[:])
print('a[:5]為', a[:5])
print('a[5:]為', a[5:])
print('a[:-5]為', a[:-5])
print('a[-5:]為', a[-5:])
print('a[0:4]為', a[0:4])
print('a[-5:-3]為', a[-5:-3])
print('a[1:10:3]為', a[1:10:3])
print('a[-1:-4:-1]為', a[-1:-4:-1])
print('a[::-1]為', a[::-1])