# -*- coding: utf-8 -*-
"""week4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qWQllpST-UZ-PhUclen3PQrq2cRilxx6
"""

print(a)

a=1
a

a="Python"
a

a

print(a,id(a))

x=1
y=2
id(x)

id(y)

z=1
id(z)

0.1+0.1+0.1

bool(1)

bool(0)

a=123
b=123.456
c="Python"

print(a)
print("a=",a)

print(a,end="   ")

print("123\n 456")

print("123\t456")

s=input()

a=input("ENTER YOUR NAME:")

a=int(input("ENTER YOUR NAMER"))

a+1

#KAMI SAMA

x=1
y=[1,2,3]
print(x in y)

