# -*- coding: utf-8 -*-
"""week3-A108260052-翁偉倫.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJGydi0kwYquiuoGsJMqSR4ypOwV2MIs
"""

print("Hello World")

print("我是翁偉倫")