# -*- coding: utf-8 -*-
"""week45舊版.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1969764j6MS2e6RfMd2b4evlkIl7ZWugz
"""

a=int(input("第一次期中考成績"))
b=int(input("第二次期中考成績"))
c=int(input("期末考成績"))
print(a+b+c)
print((a+b+c)/3)

d=int(input("請輸入幾尺"))
print(d,"尺")
e=int(input("請輸入幾吋"))
print(e,"吋")
f=(d*)