# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mBtEbwdORya8Lm3uiaYrteE0zQFRvDSM
"""

n = int(input('請輸入n值?'))
sum = 0;
for i in range(1,n+1):
    sum = sum + i*i;
print(sum)

a = int(input("請輸入第1個數字:"))
b = int(input("請輸入第2個數字:"))
for c in range(a, 1, -1):
    if (a % c == 0 and b % c == 0):
       break
print("最大公約數 GCD =", c)
for c in range(a, a * b):
    if (c % a == 0 and c % b == 0):
       break
print("最小公倍數 LCM =", c)

num = int(input('輸入求第幾項費氏數列?'))
a = 1
b = 1
print(1,a)
for i in range(2, num+1):
    a, b = b, a+b
    print(i, a)

import random
while True:
    dice = random.randint(1,6)
    print(dice)
    if dice == 6:
       break

for i in range(1,10,1):
     for j in range(1,10,1):
          print(i, '*', j, '=', i*j, '\t', sep='',end='')
     print()

for i in range(1,10,1):
    for j in range(1,10,1):
        print(i, '*', j, '=', i*j, '\t', sep='',end='')
    print()
i = 0
while i < 9:
    i = i + 1
    j = 1
    while j < 10:
        print(i, '*', j, '=', i*j, '\t', sep='',end='')
        j = j + 1
    print( )

for i in range(1,6):
    print(i)
    if i == 3:
        break

i = 0
while (i<5):
    i += 1
    if i == 3:
        continue
    print(i)

i = 1
while (i<6):
    print(i)
    if i == 6:
        break
    i += 1
else:
    print('while迴圈正常結束')

n = 0
for x in [0,1,2,3]:
    if x%2 == 0:
        continue
        n += 1
    print("執行的元素是", x)